server:
  port: 8889

spring:
  application:
    name: config-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cherish8513/shop-example-msa-by-kotlin.git

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
