server:
  port: 33333

spring:
  application:
    name: user-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mariadb://k6a308.p.ssafy.io:3306/yliad?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: root
    password: root!
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        show_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k6a308.p.ssafy.io:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

greeting:
  message: Welcome to the Simple E-Commerce.

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, busrefresh
